### ISSUE TITLE
Where do you stand with Webpack, typescript, etc

### ISSUE THREAD

**Issue by fephil** [furzeface/framewerk#1]
I don't have the time or the same enthusiasm to hand make a static site generator so I'm more inclined to use someone elses.

Do you have plans to include Webpack and/or typescript?

**Comment by furzeface** [comment]
**Webpack** yes definitely on the list.

**TypeScript** no - happy to write JavaScript in ES6 without typings etc and transpile. I don't think it's worth it to be honest to add it but maybe it could be an option. Do you have a compelling case for TypeScript in this situation?

**Comment by fephil** [comment]
It depends what the situation is. I think TS brings a lot of benefits to writing javascript (just for the autocomplete alone). However, it's heavy for just quick one off prototypes.

**Comment by furzeface** [comment]
Ok maybe TS version coming soon @fephil. :octocat:

**Comment by furzeface** [comment]
Closed and created #7 and #8 as enhancements.
